"""empty message

Revision ID: 050428edfb34
Revises: 163d4c14bce7
Create Date: 2026-06-10 19:45:09.442899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '050428edfb34'
down_revision = '163d4c14bce7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
