"""add google tokens to user

Revision ID: 71687e18eb37
Revises: 050428edfb34
Create Date: 2026-06-22 20:51:27.875377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71687e18eb37'
down_revision = '050428edfb34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_access_token', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('google_refresh_token', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('google_refresh_token')
        batch_op.drop_column('google_access_token')

    # ### end Alembic commands ###
